program easyone;

uses
  Windows,
  SysUtils,
  Vcl.Forms,
  Model.Email in 'Model\Model.Email.pas',
  Model.Empresa in 'Model\Model.Empresa.pas',
  Model.Produto in 'Model\Model.Produto.pas',
  UConeSul in 'Utils\UConeSul.pas',
  uJKDialog in 'Utils\uJKDialog.pas',
  uRotinasComuns in 'Utils\uRotinasComuns.pas' {DMRotinas: TDataModule},
  Vcl.Loading in 'Utils\Vcl.Loading.pas',
  Vcl.Navigation in 'Utils\Vcl.Navigation.pas',
  Vcl.Session in 'Utils\Vcl.Session.pas',
  UnitLocalizacaoCad in 'Form\Cadastro\UnitLocalizacaoCad.pas' {FrmLocalizacaoCad},
  UnitEmpresa in 'Form\Acesso\UnitEmpresa.pas' {FrmEmpresa},
  UnitEmpresaRegistro in 'Form\Acesso\UnitEmpresaRegistro.pas' {FrmRegistroEmpresa},
  UnitLogin in 'Form\Acesso\UnitLogin.pas' {FrmLogin},
  UnitPerfil in 'Form\Acesso\UnitPerfil.pas' {FrmPerfil},
  UnitPerfilCad in 'Form\Acesso\UnitPerfilCad.pas' {FrmPerfilCad},
  UnitPermissao in 'Form\Acesso\UnitPermissao.pas' {FrmPermissao},
  UnitUsuario in 'Form\Acesso\UnitUsuario.pas' {FrmUsuario},
  UnitUsuarioCad in 'Form\Acesso\UnitUsuarioCad.pas' {FrmUsuarioCad},
  UDM in 'DM\UDM.pas' {DM: TDataModule},
  uFormsDialogs in 'Form\FormModelo\uFormsDialogs.pas',
  UnitFuncionario in 'Form\Consulta\UnitFuncionario.pas' {FrmFuncionario},
  UnitFuncionarioCad in 'Form\Cadastro\UnitFuncionarioCad.pas' {FrmFuncionarioCad},
  UnitProdutoCad in 'Form\Cadastro\UnitProdutoCad.pas' {FrmProdutoCad},
  UnitPrazoCad in 'Form\Cadastro\UnitPrazoCad.pas' {FrmPrazoCad},
  UnitMarcaCad in 'Form\Cadastro\UnitMarcaCad.pas' {FrmMarcaCad},
  UnitTipoPlano in 'Form\Consulta\UnitTipoPlano.pas' {FrmTipoPlano},
  UnitLocalizacao in 'Form\Consulta\UnitLocalizacao.pas' {FrmLocalizacao},
  UnitMarca in 'Form\Consulta\UnitMarca.pas' {FrmMarca},
  UnitProduto in 'Form\Consulta\UnitProduto.pas' {FrmProdutos},
  UnitPrazo in 'Form\Consulta\UnitPrazo.pas' {FrmPrazo},
  UnitManifesto in 'Form\Manifesto\UnitManifesto.pas' {FrmManifesto},
  UnitPedidoCad in 'Form\Pedido\UnitPedidoCad.pas' {FrmPedidoCad},
  UnitConfiguracaoBancoDados in 'Form\Acesso\UnitConfiguracaoBancoDados.pas' {FrmConfiguracaoBancodados},
  Model.Socio in 'Model\Model.Socio.pas',
  UnitPessoas in 'Form\Consulta\UnitPessoas.pas' {FrmPessoa},
  UnitPessoaCad in 'Form\Cadastro\UnitPessoaCad.pas' {FrmPessoaCad},
  Model.Relatorio in 'ModelRelatorio\Model.Relatorio.pas',
  UnitUnidade in 'Form\Consulta\UnitUnidade.pas' {FrmUnidade},
  UnitUnidadeCad in 'Form\Cadastro\UnitUnidadeCad.pas' {FrmUnidadeCad},
  UnitImpressao in 'Form\Pedido\UnitImpressao.pas' {FrmImpressao},
  UnitQrCodeWhatsApp in 'Form\Sistema\UnitQrCodeWhatsApp.pas' {FrmQrCodeWhatsApp},
  UnitFrmEmail in 'Form\Sistema\UnitFrmEmail.pas' {FrmEnviarEmail},
  UnitFrmWhatsAppMassa in 'Form\Sistema\UnitFrmWhatsAppMassa.pas' {FrmEnviarWhatsAppMassa},
  UDMRelatorio in 'DM\UDMRelatorio.pas' {DMRelatorio: TDataModule},
  UnitFrmWhatsAppMSG in 'Form\Sistema\UnitFrmWhatsAppMSG.pas' {FrmEnviarWhatsAppMSG},
  Model.Sede_old in 'Model\Model.Sede_old.pas',
  UnitEnderecoCad in 'Form\Cadastro\UnitEnderecoCad.pas' {FrmEnderecoCad},
  UnitPessoaAdicionar in 'Form\Consulta\UnitPessoaAdicionar.pas' {FrmPessoaAdicionar},
  UnitAssociadoCad in 'Form\Cadastro\UnitAssociadoCad.pas' {FrmAssociadoCad},
  AppVendas in 'AppVendas\AppVendas.pas',
  UnitPedido in 'Form\Pedido\UnitPedido.pas' {FrmPedido},
  UnitEmailCad in 'Form\Acesso\UnitEmailCad.pas' {FrmEmailCad},
  UnitGlobal in 'Utils\UnitGlobal.pas',
  UnitBaseRelatorio in 'Form\FormBase\UnitBaseRelatorio.pas' {FrmBaseRelatorio},
  Model.ConfNF in 'Model\Model.ConfNF.pas',
  Model.Tipoplano in 'Model\Model.Tipoplano.pas',
  Model.SubGrupoPlano in 'Model\Model.SubGrupoPlano.pas',
  Model.SQLQry in 'Model\Model.SQLQry.pas',
  UnitGrupo in 'Form\Consulta\UnitGrupo.pas' {FrmGrupo},
  UnitGrupoCad in 'Form\Cadastro\UnitGrupoCad.pas' {FrmGrupoCad},
  UnitTipoCad in 'Form\Cadastro\UnitTipoCad.pas' {FrmTipoCad},
  UnitGrupoPlanoCad in 'Form\Cadastro\UnitGrupoPlanoCad.pas' {FrmGrupoPlanoCad},
  UnitPlanoContaCad in 'Form\Cadastro\UnitPlanoContaCad.pas' {FrmPlanoCad},
  Model.GrupoPlano in 'Model\Model.GrupoPlano.pas',
  UnitBaseCons in 'Form\FormBase\UnitBaseCons.pas' {FrmModeloConsulta},
  UnitPlanoConta in 'Form\Consulta\UnitPlanoConta.pas' {FrmPlanoContaCons},
  UnitSubGrupoCad in 'Form\Cadastro\UnitSubGrupoCad.pas' {FrmSubgrupoCad},
  UnitTransportadora in 'Form\Consulta\UnitTransportadora.pas' {FrmTransportadoraConsulta},
  UnitTransportadoraCad in 'Form\Cadastro\UnitTransportadoraCad.pas' {FrmTransportadoraCad},
  Model.Contas in 'Model\Model.Contas.pas',
  UnitContas in 'Form\Consulta\UnitContas.pas' {FrmContas},
  UnitContaCad in 'Form\Cadastro\UnitContaCad.pas' {FrmContasCad},
  ULivroCaixa in 'Form\Financeiro\ULivroCaixa.pas' {FrmLivroCaixa},
  UnitLivroCaixaCad in 'Form\Financeiro\UnitLivroCaixaCad.pas' {FrmLivroCaixaCad},
  Model.LivroCaixa in 'Model\Model.LivroCaixa.pas',
  Model.Custo in 'Model\Model.Custo.pas',
  UnitCentroCustoCad in 'Form\Financeiro\UnitCentroCustoCad.pas' {FrmCustoCad},
  UnitConfiguracao in 'Form\Acesso\UnitConfiguracao.pas' {FrmConfiguracao},
  Vcl.Validacoes in 'Utils\Vcl.Validacoes.pas',
  UnitAlterarSenha in 'Form\Acesso\UnitAlterarSenha.pas' {FrmAlterarSenha},
  UnitFrmMensagem in 'Form\Sistema\UnitFrmMensagem.pas' {FrmMensagem},
  UnitMensagemCad in 'Form\Sistema\UnitMensagemCad.pas' {FrmMensagemCad},
  UnitConfiguracaoTerminal in 'Form\Acesso\UnitConfiguracaoTerminal.pas' {FrmConfiguracaoTerminal},
  Model.Atualizacao in 'Model\Model.Atualizacao.pas',
  UnitAssociadoAdicionar in 'Form\Consulta\UnitAssociadoAdicionar.pas' {FrmAssociadoAdicionar},
  UnitRelacaoAniversariante in 'Form\Consulta\UnitRelacaoAniversariante.pas' {FrmRelacaoniverConsulta},
  UnitFrmNotificacaoAPP in 'Form\Associacao\UnitFrmNotificacaoAPP.pas' {FrmEnviarNotificacao},
  OAuth2.Gmail in 'Form\OAuth2.Gmail.pas',
  OAuth2.Outlook in 'Form\OAuth2.Outlook.pas',
  OAuth2 in 'Form\OAuth2.pas',
  EnvioZap in 'Utils\EnvioZap.pas',
  UnitAtualizacaoCadastro in 'Form\ModuloAssociaao\Sindicato\UnitAtualizacaoCadastro.pas' {FrmAssociadoAtualizacao},
  UnitBaseCadCons in 'Form\FormBase\UnitBaseCadCons.pas' {FrmBaseCadCons},
  Model.SindLotacao in 'Model\Model.SindLotacao.pas',
  Model.SindEmpresa in 'Model\Model.SindEmpresa.pas',
  Model.SindProfissao in 'Model\Model.SindProfissao.pas',
  UnitSede in 'Form\Consulta\UnitSede.pas' {FrmSede},
  UnitSedeCad in 'Form\Cadastro\UnitSedeCad.pas' {FrmSedeCad},
  UnitDashBoard in 'Form\Sistema\UnitDashBoard.pas' {FrmDashBoard},
  Model.Campanha in 'Model\Model.Campanha.pas',
  Model.Candidato in 'Model\Model.Candidato.pas',
  Model.Membro in 'Model\Model.Membro.pas',
  UnitDependentesCad in 'Form\Associacao\UnitDependentesCad.pas' {FrmDependentesCad},
  Model.SindDependente in 'Model\Model.SindDependente.pas',
  UnitVeiculoEntradaPagamento in 'Form\Garagem\Operacoes\UnitVeiculoEntradaPagamento.pas' {FrmEntradaVeiculoPagamento},
  UnitCarteirinha in 'Form\Carteirinha\UnitCarteirinha.pas' {FrmCarteira},
  Model.Carteirinha in 'Model\Model.Carteirinha.pas',
  UnitCadCarteiraDependente in 'Form\Carteirinha\UnitCadCarteiraDependente.pas' {FrmCarteiraCadDependente},
  UnitConsNFe in 'Form\Fiscal\UnitConsNFe.pas' {FrmConsultaNFe},
  Model.NFE in 'Model\Model.NFE.pas',
  APP.Asmuv in 'AppVendas\APP.Asmuv.pas',
  UDMAPP in 'DM\UDMAPP.pas' {DMAPP: TDataModule},
  UConsultaReceber in 'Form\Financeiro\UConsultaReceber.pas' {FrmConsReceber},
  ULancReceber in 'Form\Financeiro\ULancReceber.pas' {FrmLancReceber},
  UGerador in 'Form\Sistema\UGerador.pas' {FrmGerador},
  UnitEstatistica in 'Form\Associacao\UnitEstatistica.pas' {FrmEstatisticas},
  UnitControleBancario in 'Form\Financeiro\ControleBancario\UnitControleBancario.pas' {FrmControleBancario},
  UnitTicketsCad in 'Form\Associacao\UnitTicketsCad.pas' {FrmTicketsCad},
  UnitConsConvenio in 'Form\Associacao\UnitConsConvenio.pas' {FrmConConveio},
  UnitCadConvenio in 'Form\Associacao\UnitCadConvenio.pas' {FrmCadConvenio},
  UnitCadCarteira in 'Form\Carteirinha\UnitCadCarteira.pas' {FrmCarteiraCad},
  UnitFrmWhatsApp in 'Form\Sistema\UnitFrmWhatsApp.pas' {FrmEnviarWhatsApp},
  Controllers.Auth in 'Utils\Controllers.Auth.pas',
  uSincronizacaoZap in 'Utils\uSincronizacaoZap.pas',
  UnitConsRegistroEntrada in 'Form\Associacao\UnitConsRegistroEntrada.pas' {FrmRegistroEntrada},
  Model.Avisos in 'Model\Model.Avisos.pas',
  UnitAvisoPessoa in 'Form\Avisos\UnitAvisoPessoa.pas' {FrmAvisoPessoa},
  UnitAutorizacao in 'Form\Associacao\UnitAutorizacao.pas' {FrmAutorizacao},
  UnitCadAutorizacao in 'Form\Associacao\UnitCadAutorizacao.pas' {FrmCadAutorizacao},
  Model.Tickets_old in 'Model\Model.Tickets_old.pas',
  UnitAvisoDependente in 'Form\Avisos\UnitAvisoDependente.pas' {FrmAvisoDependente},
  UnitBaseOperacoes in 'Form\FormBase\UnitBaseOperacoes.pas' {FrmBaseOperacoes},
  UnitRelatorioTicket in 'Form\Relatorio\UnitRelatorioTicket.pas' {FrmRelatorioTicket},
  Vcl.PermissaoUsuario in 'Utils\Vcl.PermissaoUsuario.pas',
  UnitVeiculoFoto in 'Form\Garagem\Anexo\UnitVeiculoFoto.pas' {FrmVeiculoFoto},
  UnitBaixaTicket in 'Form\Associacao\UnitBaixaTicket.pas' {FrmBaixaTicket},
  UnitAssociadoConvenio in 'Form\Associacao\UnitAssociadoConvenio.pas' {FrmAssociadoConvenio},
  TelaFuncoes in 'Utils\TelaFuncoes.pas',
  UnitCadTipoVeiculo in 'Form\Garagem\Cadastro\UnitCadTipoVeiculo.pas' {FrmCadTipoVeiculo},
  UnitCadEspecieVeiculo in 'Form\Garagem\Cadastro\UnitCadEspecieVeiculo.pas' {FrmCadEspecieVeiculo},
  UnitCadMarcaVeiculo in 'Form\Garagem\Cadastro\UnitCadMarcaVeiculo.pas' {FrmCadMarcaVeiculo},
  UnitCadModeloVeiculo in 'Form\Garagem\Cadastro\UnitCadModeloVeiculo.pas' {FrmCadModeloVeiculo},
  UnitGerenciarVeiculo in 'Form\Garagem\Gerenciamento\UnitGerenciarVeiculo.pas' {FrmGerenciarVeiculo},
  UnitGerenciarFichaPessoa in 'Form\Garagem\Gerenciamento\UnitGerenciarFichaPessoa.pas' {FrmGerenciarFichaPessoa},
  UnitGerenciarInteresse in 'Form\Garagem\Gerenciamento\UnitGerenciarInteresse.pas' {FrmGerenciarInteresse},
  UnitConsHistoricoVeiculo in 'Form\Garagem\Consulta\UnitConsHistoricoVeiculo.pas' {FrmConsHistoricoVeiculo},
  UnitConsHistoricoConsignado in 'Form\Garagem\Consulta\UnitConsHistoricoConsignado.pas' {FrmConsHistoricoConsignado},
  UnitGerenciarVendaVeiculo in 'Form\Garagem\Gerenciamento\UnitGerenciarVendaVeiculo.pas' {FrmGerenciarVendaVeiculo},
  UnitGerenciarPendencia in 'Form\Garagem\Gerenciamento\UnitGerenciarPendencia.pas' {FrmGerenciarPendencia},
  UnitGerenciarCompraVeiculo in 'Form\Garagem\Gerenciamento\UnitGerenciarCompraVeiculo.pas' {FrmGerenciarCompraVeiculo},
  UnitCadVeiculo in 'Form\Garagem\Cadastro\UnitCadVeiculo.pas' {FrmCadVeiculo},
  UnitEntradaVeiculo in 'Form\Garagem\Operacoes\UnitEntradaVeiculo.pas' {FrmEntradaVeiculo},
  Model.Compra in 'Model\Model.Compra.pas',
  UnitPedidoItens in 'Form\Pedido\UnitPedidoItens.pas' {FrmPedidoItens},
  Model.Gerais in '..\EasyBot\Form\Model\Model.Gerais.pas',
  Constantes in '..\EasyBot\Units\Constantes.pas',
  UnitBaseCad in 'Form\FormBase\UnitBaseCad.pas' {FrmBaseCad},
  UnitBaseAnexo in 'Form\FormBase\UnitBaseAnexo.pas' {FrmAnexoPadrao},
  UnitVeiculoAnexoDoc in 'Form\Garagem\Anexo\UnitVeiculoAnexoDoc.pas' {FrmVeiculoAnexoDoc},
  UnitVeiculoEntrada in 'Form\Garagem\Operacoes\UnitVeiculoEntrada.pas' {FrmEntradaVeiculoSelecionar},
  Model.Geral in 'Model\Model.Geral.pas',
  Model.TipoDocumento in 'Form\ModelE\Model.TipoDocumento.pas',
  DAO.Generico in 'Form\Dao\DAO.Generico.pas',
  uAtributosRTTI in 'Form\ModelE\uAtributosRTTI.pas',
  UnitConsultaTipoDocumento in 'Form\Consulta\UnitConsultaTipoDocumento.pas' {FrmConsultaTipoDocumento},
  UnitCadTipoDocumento in 'Form\Cadastro\UnitCadTipoDocumento.pas' {FrmCadTipoDocumento},
  Model.EntradaVeiculo in 'Form\ModelE\Model.EntradaVeiculo.pas',
  DAO.Utilitarios in 'Form\Dao\DAO.Utilitarios.pas',
  Dao.Operacoes in 'Form\Dao\Dao.Operacoes.pas',
  Model.EntradaVeiculoItens in 'Form\ModelE\Model.EntradaVeiculoItens.pas',
  Model.EntradaVeiculoFinanceiro in 'Form\ModelE\Model.EntradaVeiculoFinanceiro.pas',
  uConfiguracaoService in 'Form\Service\uConfiguracaoService.pas',
  Model.LogVeiculo in 'Form\ModelE\Model.LogVeiculo.pas',
  Model.VeiculosAtualizar in 'Form\ModelE\Model.VeiculosAtualizar.pas',
  Model.EstoqueGeral in 'Form\ModelE\Model.EstoqueGeral.pas',
  Model.Mensagem_Whatsapp in 'Form\ModelE\Model.Mensagem_Whatsapp.pas',
  MensagemZap.V1 in '..\EasyBot\Units\MensagemZap.V1.pas',
  ULancOrdemservico in 'Form\Ordem_Servico\ULancOrdemservico.pas' {FrmRecpOrdemServico},
  UDiagOrdemServico in 'Form\Ordem_Servico\UDiagOrdemServico.pas' {FrmTecnOrdemServico},
  Model.OrdemServico in 'Form\ModelE\Model.OrdemServico.pas',
  UGerOrdemServico in 'Form\Ordem_Servico\UGerOrdemServico.pas' {FrmGerOrdemServico},
  UVariaveisMensagem in 'Utils\UVariaveisMensagem.pas',
  Model.TabProduto in 'Form\ModelE\Model.TabProduto.pas',
  Model.HistoricoEquipamento in 'Form\ModelE\Model.HistoricoEquipamento.pas',
  UnitBasePesquisa in 'Form\FormBase\UnitBasePesquisa.pas' {FrmBasePesquisa},
  UFrmPesquisaCliente in 'Form\Pesquisa\UFrmPesquisaCliente.pas' {FrmPesquisaCliente},
  Model.Carteira in 'Form\ModelE\Model.Carteira.pas',
  UnitLogsMensagem in 'Form\Logs\UnitLogsMensagem.pas' {FrmLogsMensagem},
  Model.Receber in 'Form\ModelE\Model.Receber.pas',
  Model.Receber.PlanoContas in 'Form\ModelE\Model.Receber.PlanoContas.pas',
  UBaixaReceber in 'Form\Financeiro\UBaixaReceber.pas' {FrmBaixaReceber},
  UFormNovoBase in 'Form\FormBase\UFormNovoBase.pas' {FormNovoBase},
  UFormNovoBasePesquisa in 'Form\FormBase\UFormNovoBasePesquisa.pas' {FormNovoBasePesquisa},
  UFormNovoBaseGerenciamento in 'Form\FormBase\UFormNovoBaseGerenciamento.pas' {FormNovoBaseGerenciamento},
  UnitStyles in 'Form\FormBase\UnitStyles.pas' {FormStyles},
  Vcl.Themes,
  Vcl.Styles,
  UnitPrincipalNew in 'Form\PrincipalPedido\UnitPrincipalNew.pas' {FrmPrincipalNew},
  UnitBaseNovoCadastro in 'Form\FormBase\UnitBaseNovoCadastro.pas' {FormNovoBaseCadastro},
  UnitCadCFOP in 'Form\Cadastro\UnitCadCFOP.pas' {FrmCadCFOP},
  UnitPesqCFOP in 'Form\Consulta\UnitPesqCFOP.pas' {FrmPesqCFOP},
  UOpenFormulario in 'Utils\UOpenFormulario.pas',
  Model.CFOP in 'Form\ModelE\Model.CFOP.pas',
  uAppMigrations in 'Migrations\uAppMigrations.pas',
  uDbMigrations in 'Migrations\uDbMigrations.pas',
  Dao.CFOP in 'Form\Dao\Dao.CFOP.pas',
  UnitPesqCidade in 'Form\Consulta\UnitPesqCidade.pas' {FrmPesCidade},
  UnitCadCidade in 'Form\Cadastro\UnitCadCidade.pas' {FrmCadCidade},
  Model.Cidade in 'Form\ModelE\Model.Cidade.pas',
  Model.ContasBancaria in 'Form\ModelE\Model.ContasBancaria.pas',
  Dao.ContaBancaria in 'Form\Dao\Dao.ContaBancaria.pas',
  Model.Empresas in 'Form\ModelE\Model.Empresas.pas',
  Dao.Empresa in 'Form\Dao\Dao.Empresa.pas',
  UnitCadEmpresa in 'Form\Acesso\UnitCadEmpresa.pas' {FrmCadEmpresa},
  UnitComponentes in 'Form\FormBase\UnitComponentes.pas' {FrmComponents},
  UCEPService in 'Form\Service\UCEPService.pas',
  UnitPesqEmpresa in 'Form\Acesso\UnitPesqEmpresa.pas' {FormPesqEmpresa},
  Model.Funcionario in 'Form\ModelE\Model.Funcionario.pas',
  Dao.Funcionario in 'Form\Dao\Dao.Funcionario.pas',
  Dao.PrazoPag in 'Form\Dao\Dao.PrazoPag.pas',
  Model.PrazoPag in 'Form\ModelE\Model.PrazoPag.pas',
  Dao.Grupo in 'Form\Dao\Dao.Grupo.pas',
  Dao.Localizacao in 'Form\Dao\Dao.Localizacao.pas',
  Dao.Unidade in 'Form\Dao\Dao.Unidade.pas',
  Dao.PlanoContas in 'Form\Dao\Dao.PlanoContas.pas',
  Dao.Marca in 'Form\Dao\Dao.Marca.pas',
  Dao.Transportadora in 'Form\Dao\Dao.Transportadora.pas',
  Dao.Produto in 'Form\Dao\Dao.Produto.pas',
  Dao.Pessoa in 'Form\Dao\Dao.Pessoa.pas',
  Controller.Carteira in 'Form\Controllers\Controller.Carteira.pas',
  Controller.CFOP in 'Form\Controllers\Controller.CFOP.pas',
  Controller.Cidade in 'Form\Controllers\Controller.Cidade.pas',
  Controller.ContaBancaria in 'Form\Controllers\Controller.ContaBancaria.pas',
  Controller.Empresa in 'Form\Controllers\Controller.Empresa.pas',
  Controller.EntradaVeiculo in 'Form\Controllers\Controller.EntradaVeiculo.pas',
  Controller.EntradaVeiculoFinanceiro in 'Form\Controllers\Controller.EntradaVeiculoFinanceiro.pas',
  Controller.EntradaVeiculoItens in 'Form\Controllers\Controller.EntradaVeiculoItens.pas',
  Controller.Funcionario in 'Form\Controllers\Controller.Funcionario.pas',
  Controller.Grupo in 'Form\Controllers\Controller.Grupo.pas',
  Controller.HistoricoEquipamento in 'Form\Controllers\Controller.HistoricoEquipamento.pas',
  Controller.Localizacao in 'Form\Controllers\Controller.Localizacao.pas',
  Controller.LogVeiculo in 'Form\Controllers\Controller.LogVeiculo.pas',
  Controller.LookupHelper in 'Form\Controllers\Controller.LookupHelper.pas',
  Controller.Marca in 'Form\Controllers\Controller.Marca.pas',
  Controller.Mensagem_Whatsapp in 'Form\Controllers\Controller.Mensagem_Whatsapp.pas',
  Controller.Pessoa in 'Form\Controllers\Controller.Pessoa.pas',
  Controller.PlanoContas in 'Form\Controllers\Controller.PlanoContas.pas',
  Controller.PrazoPag in 'Form\Controllers\Controller.PrazoPag.pas',
  Controller.Produto in 'Form\Controllers\Controller.Produto.pas',
  Controller.Receber in 'Form\Controllers\Controller.Receber.pas',
  Controller.Receber.PlanoContas in 'Form\Controllers\Controller.Receber.PlanoContas.pas',
  Controller.TipoDocumento in 'Form\Controllers\Controller.TipoDocumento.pas',
  Controller.Transportadora in 'Form\Controllers\Controller.Transportadora.pas',
  Controller.Unidade in 'Form\Controllers\Controller.Unidade.pas',
  Controller.Veiculos in 'Form\Controllers\Controller.Veiculos.pas',
  Controllers.OrdemServico in 'Form\Controllers\Controllers.OrdemServico.pas',
  Model.Localizacao in 'Form\ModelE\Model.Localizacao.pas',
  Model.Grupo in 'Form\ModelE\Model.Grupo.pas',
  Model.Marca in 'Form\ModelE\Model.Marca.pas',
  Model.Unidade in 'Form\ModelE\Model.Unidade.pas',
  Model.PlanoConta in 'Form\ModelE\Model.PlanoConta.pas',
  Model.Pessoa in 'Form\ModelE\Model.Pessoa.pas',
  Model.Sindicato_Dependentes in 'Form\ModelE\Model.Sindicato_Dependentes.pas',
  Controller_sindicato_dependente in 'Form\Controllers\Controller_sindicato_dependente.pas',
  Dao_Sindicato_Dependentes in 'Form\Dao\Dao_Sindicato_Dependentes.pas',
  Dao.Carteira in 'Form\Dao\Dao.Carteira.pas',
  Dao_Sindicato_Empresa in 'Form\Dao\Dao_Sindicato_Empresa.pas',
  Model.Sindicato_Empresa in 'Form\ModelE\Model.Sindicato_Empresa.pas',
  Controller_sindicato_empresa in 'Form\Controllers\Controller_sindicato_empresa.pas',
  Dao_Secretaria in 'Form\Dao\Dao_Secretaria.pas',
  Model.Secretaria in 'Form\ModelE\Model.Secretaria.pas',
  Controller_secretaria in 'Form\Controllers\Controller_secretaria.pas',
  Dao_Sindicato_Profissao in 'Form\Dao\Dao_Sindicato_Profissao.pas',
  Model.Sindicato_Profissao in 'Form\ModelE\Model.Sindicato_Profissao.pas',
  Controller_sindicato_profissao in 'Form\Controllers\Controller_sindicato_profissao.pas',
  UnitEmpCad in 'Form\ModuloAssociaao\Sindicato\UnitEmpCad.pas' {FrmEmpCad},
  UnitSecretariaCadn in 'Form\ModuloAssociaao\Sindicato\UnitSecretariaCadn.pas' {FrmSecretariaCadN},
  UniProfissaoCad in 'Form\ModuloAssociaao\Sindicato\UniProfissaoCad.pas' {FrmProfissaoCad},
  UnitLotacaoCad in 'Form\ModuloAssociaao\Sindicato\UnitLotacaoCad.pas' {FrmLotacaoCad},
  Dao_Sindicato_Lotacao in 'Form\Dao\Dao_Sindicato_Lotacao.pas',
  Model.Sindicato_Lotacao in 'Form\ModelE\Model.Sindicato_Lotacao.pas',
  Controller_sindicato_lotacao in 'Form\Controllers\Controller_sindicato_lotacao.pas',
  Dao_Sede in 'Form\Dao\Dao_Sede.pas',
  Model.Sede in 'Form\ModelE\Model.Sede.pas',
  Controller_sede in 'Form\Controllers\Controller_sede.pas',
  Model.Ticket in 'Form\ModelE\Model.Ticket.pas',
  Controller.Ticket in 'Form\Controllers\Controller.Ticket.pas',
  Dao.Ticket in 'Form\Dao\Dao.Ticket.pas',
  Dao_Convenio in 'Form\Dao\Dao_Convenio.pas',
  Controller_convenio in 'Form\Controllers\Controller_convenio.pas',
  Model.Convenio in 'Form\ModelE\Model.Convenio.pas',
  UFormNovoBaseDiversos in 'Form\FormBase\UFormNovoBaseDiversos.pas' {FormNovoBaseDiversos},
  ULogsSincronizacao in 'Form\Logs\ULogsSincronizacao.pas' {FrmLogs},
  Model.Sincronizar in 'Form\ModelE\Model.Sincronizar.pas',
  Controller_Sincronizar in 'Form\Controllers\Controller_Sincronizar.pas',
  Model.Notificacao in 'Form\ModelE\Model.Notificacao.pas',
  Controller.NotificacaoAPP in 'Form\Controllers\Controller.NotificacaoAPP.pas',
  Model.Autorizacao in 'Form\ModelE\Model.Autorizacao.pas',
  Dao.autorizacao in 'Form\Dao\Dao.autorizacao.pas',
  Controller.Autorizacao in 'Form\Controllers\Controller.Autorizacao.pas',
  Controller.Estatisticas in 'Form\Controllers\Controller.Estatisticas.pas',
  Model.Estatisticas in 'Form\ModelE\Model.Estatisticas.pas',
  Model.Sindicato_Registro in 'Form\ModelE\Model.Sindicato_Registro.pas',
  Controllers.SindRegistro in 'Form\Controllers\Controllers.SindRegistro.pas',
  UnitBaseNovoPesquisaDiversos in 'Form\FormBase\UnitBaseNovoPesquisaDiversos.pas' {FormNovoBasePesquisaDiversas},
  Model.Usuario in 'Form\ModelE\Model.Usuario.pas',
  Controller_usuario in 'Form\Controllers\Controller_usuario.pas',
  Dao_Usuario in 'Form\Dao\Dao_Usuario.pas',
  Controller_perfil in 'Form\Controllers\Controller_perfil.pas',
  Dao_Perfil in 'Form\Dao\Dao_Perfil.pas',
  Model.Perfil in 'Form\ModelE\Model.Perfil.pas',
  Controller_mensagem in 'Form\Controllers\Controller_mensagem.pas',
  Dao_Mensagem in 'Form\Dao\Dao_Mensagem.pas',
  Model.Mensagem in 'Form\ModelE\Model.Mensagem.pas',
  UnitEleicaoEleitor in 'Form\Eleicao\View\UnitEleicaoEleitor.pas' {FrmEleicaoEleitores},
  UnitEleicaoCad in 'Form\Eleicao\Form\UnitEleicaoCad.pas' {FrmEleicaoCad},
  Model.Eleicao in 'Form\Eleicao\Model\Model.Eleicao.pas',
  Controller.Eleicao in 'Form\Eleicao\Controller\Controller.Eleicao.pas',
  UnitEleicaoConfiguracao in 'Form\Eleicao\Form\UnitEleicaoConfiguracao.pas' {FrmEleicaoConfiguracao},
  Model.EleicaoConfig in 'Form\Eleicao\Model\Model.EleicaoConfig.pas',
  Controller.EleicaoConfig in 'Form\Eleicao\Controller\Controller.EleicaoConfig.pas',
  Dao.EleicaoConfig in 'Form\Eleicao\Dao\Dao.EleicaoConfig.pas',
  UnitAssembleiaPauta in 'Form\Eleicao\Form\UnitAssembleiaPauta.pas' {FrmAssembleiaPauta},
  Model.EleicaoChapa in 'Form\Eleicao\Model\Model.EleicaoChapa.pas',
  Controller.EleicaoChapa in 'Form\Eleicao\Controller\Controller.EleicaoChapa.pas',
  Model.Transportadora in 'Form\ModelE\Model.Transportadora.pas',
  Dao.Pedido in 'Form\Dao\Pedido\Dao.Pedido.pas',
  Dao.PedidoItens in 'Form\Dao\Pedido\Dao.PedidoItens.pas',
  Controller.Pedido in 'Form\Controllers\Pedido\Controller.Pedido.pas',
  Controller.PedidoItens in 'Form\Controllers\Pedido\Controller.PedidoItens.pas',
  Model.Pedido in 'Form\ModelE\Pedido\Model.Pedido.pas',
  Model.PedidoItens in 'Form\ModelE\Pedido\Model.PedidoItens.pas',
  Model.Estoque in 'Form\ModelE\Model.Estoque.pas',
  dao.estoque in 'Form\Dao\dao.estoque.pas',
  Controller.Estoque in 'Form\Controllers\Controller.Estoque.pas',
  UnitAjusteestoqueLista in 'Form\Pedido\UnitAjusteestoqueLista.pas' {FrmAjusteEstoqueLista},
  UnitHistoricoProduto in 'Form\Pedido\UnitHistoricoProduto.pas' {FrmHistoricoProduto},
  UnitProdutoEntrada in 'Form\Pedido\UnitProdutoEntrada.pas' {FrmProdutoEntrada},
  UnitProdutoEstoque in 'Form\Pedido\UnitProdutoEstoque.pas' {FrmProdutoEstoque},
  UGerenciarCompra in 'Form\Compra\UGerenciarCompra.pas' {FrmGerenciarCompra},
  UImportacaoxml in 'Form\Compra\UImportacaoxml.pas' {FrmImportacaoxml},
  UBuscarSefaz in 'Form\Compra\UBuscarSefaz.pas' {FrmBuscarSefaz},
  Service.DistribuicaoDFe.Importacao in 'Form\Service\Service.DistribuicaoDFe.Importacao.pas',
  UConsultaXMLImportado in 'Form\Compra\UConsultaXMLImportado.pas' {FrmConsultaXMLImportado},
  Model.DistribuicaoDFE in 'Form\ModelE\Model.DistribuicaoDFE.pas',
  UController.DistribuicaoDFE in 'Form\Controllers\UController.DistribuicaoDFE.pas',
  UnitRelatorioAssociado in 'Form\Relatorio\UnitRelatorioAssociado.pas' {FrmRelAssociado},
  UnitLocalTrabalhoCad in 'Form\ModuloAssociaao\Sindicato\UnitLocalTrabalhoCad.pas' {FrmLocalTrabalhoCad},
  Model.TipoSituacao in 'Form\ModelE\Sindicato\Model.TipoSituacao.pas',
  DAO.TipoSituacao in 'Form\Dao\Sindicato\DAO.TipoSituacao.pas',
  Controller.TipoSituacao in 'Form\Controllers\Sindicato\Controller.TipoSituacao.pas',
  Model.LocalTrabalho in 'Form\ModelE\Sindicato\Model.LocalTrabalho.pas',
  DAO.LocalTrabalho in 'Form\Dao\Sindicato\DAO.LocalTrabalho.pas',
  Controller.LocalTrabalho in 'Form\Controllers\Sindicato\Controller.LocalTrabalho.pas',
  UnitCategoriaCad in 'Form\Cadastro\UnitCategoriaCad.pas' {FrmCategoriaCad},
  UnitAssociado in 'Form\Consulta\UnitAssociado.pas' {FrmAssociado},
  UnitSindicatoDesfiliar in 'Form\ModuloAssociaao\Sindicato\UnitSindicatoDesfiliar.pas' {FrmSindicatoDesfiliar},
  Model.SindicatoHistorico in 'Form\ModelE\Sindicato\Model.SindicatoHistorico.pas',
  Controller.SindicatoHistorico in 'Form\Controllers\Sindicato\Controller.SindicatoHistorico.pas',
  UnitConsTickets in 'Form\Associacao\UnitConsTickets.pas' {FrmConsTickets},
  UnitBemCad in 'Form\ModuloAssociaao\Sindicato\UnitBemCad.pas' {FrmBemCad},
  DAO.Bem in 'Form\Dao\Sindicato\DAO.Bem.pas',
  Model.Bem in 'Form\ModelE\Sindicato\Model.Bem.pas',
  Controller.Bem in 'Form\Controllers\Sindicato\Controller.Bem.pas',
  UnitAnexo in 'Form\Cadastro\UnitAnexo.pas' {FrmAnexo},
  UnitHistoricoBancario in 'Form\Cadastro\UnitHistoricoBancario.pas' {FrmHistoricoBancario},
  Controller.Categoria in 'Form\Controllers\Controller.Categoria.pas',
  Dao.Categoria in 'Form\Dao\Dao.Categoria.pas',
  Model.Categoria in 'Form\ModelE\Model.Categoria.pas',
  Model.Departamento in 'Form\ModelE\Model.Departamento.pas',
  Dao.Departamento in 'Form\Dao\Dao.Departamento.pas',
  Controller.Departamento in 'Form\Controllers\Controller.Departamento.pas',
  UnitHistoricoFiliado in 'Form\ModuloAssociaao\UnitHistoricoFiliado.pas' {FrmHistoricoFiliado},
  Frame.HistoricoTimelineItem in 'Form\Frame\HistoricoAssociado\Frame.HistoricoTimelineItem.pas' {FrameHistoricoTimelineItem: TFrame},
  UnitDepartamentoCad in 'Form\Cadastro\UnitDepartamentoCad.pas' {FrmdepartamentoCad},
  Model.Anexo in 'Form\ModelE\Model.Anexo.pas',
  Controller.Anexo in 'Form\Controllers\Controller.Anexo.pas',
  DAO.Anexo in 'Form\Dao\DAO.Anexo.pas',
  UnitControleBens in 'Form\ModuloAssociaao\Sindicato\UnitControleBens.pas' {FrmControleBens},
  UnitLancamentoBancario in 'Form\Financeiro\ControleBancario\UnitLancamentoBancario.pas' {FrmLancamentoBancario},
  Model.LancamentoBancario in 'Form\ModelE\Financeiro\Model.LancamentoBancario.pas',
  Controller.LancamentoBancario in 'Form\Controllers\Financeiro\Controller.LancamentoBancario.pas',
  Model.HistoricoBancario in 'Form\ModelE\Financeiro\Model.HistoricoBancario.pas',
  Dao.HistoricoBancario in 'Form\Dao\Financeiro\Dao.HistoricoBancario.pas',
  Controller.HistoricoBancario in 'Form\Controllers\Financeiro\Controller.HistoricoBancario.pas',
  UnitTipoSituacaoCad in 'Form\ModuloAssociaao\Sindicato\UnitTipoSituacaoCad.pas' {FrmTipoSituacaoCad},
  Dao.LancamentoBancario in 'Form\Dao\Financeiro\Dao.LancamentoBancario.pas',
  UnitLerOFX in 'Form\Financeiro\ControleBancario\UnitLerOFX.pas' {FrmOFX},
  Service.OFXReader in 'Form\Service\Service.OFXReader.pas',
  UnitMembroCad in 'Form\Eleicao\Form\UnitMembroCad.pas' {FrmMembroCad},
  Model.EleicaoChapaMembro in 'Form\Eleicao\Model\Model.EleicaoChapaMembro.pas',
  Controller.EleicaoChapaMembro in 'Form\Eleicao\Controller\Controller.EleicaoChapaMembro.pas',
  uEvolutionAPI in '..\EasyBot\Units\uEvolutionAPI.pas',
  Model.EleicaoEleitor in 'Form\Eleicao\Model\Model.EleicaoEleitor.pas',
  Controller.EleicaoEleitor in 'Form\Eleicao\Controller\Controller.EleicaoEleitor.pas',
  UnitEleicao in 'Form\Eleicao\View\UnitEleicao.pas' {FrmEleicao},
  UnitEleicaoChapa in 'Form\Eleicao\Form\UnitEleicaoChapa.pas' {FrmEleicaoChapa},
  Controller.EleicaoComissao in 'Form\Eleicao\Controller\Controller.EleicaoComissao.pas',
  UnitEleicaoComissao in 'Form\Eleicao\Form\UnitEleicaoComissao.pas' {FrmEleicaoComissao},
  Frame.QuestaoEscolhaUnica in 'Form\Frame\Assembleia\Frame.QuestaoEscolhaUnica.pas' {FrameQuestaoEscolhaUnica: TFrame},
  Frame.QuestaoLista in 'Form\Frame\Assembleia\Frame.QuestaoLista.pas' {FrameQuestaoLista: TFrame},
  Frame.QuestaoMultiplaEscolha in 'Form\Frame\Assembleia\Frame.QuestaoMultiplaEscolha.pas' {FrameQuestaoMultiplaEscolha: TFrame},
  Frame.QuestaoOpcaoItem in 'Form\Frame\Assembleia\Frame.QuestaoOpcaoItem.pas' {FrameQuestaoOpcaoItem: TFrame},
  Frame.QuestaoOpcaoListaItem in 'Form\Frame\Assembleia\Frame.QuestaoOpcaoListaItem.pas' {FrameQuestaoOpcaoListaItem: TFrame},
  Frame.QuestaoOpcaoMultiplaItem in 'Form\Frame\Assembleia\Frame.QuestaoOpcaoMultiplaItem.pas' {FrameQuestaoOpcaoMultiplaItem: TFrame},
  Frame.QuestaoTextoCurto in 'Form\Frame\Assembleia\Frame.QuestaoTextoCurto.pas' {FrameQuestaoTextoCurto: TFrame},
  Frame.QuestaoTextoLongo in 'Form\Frame\Assembleia\Frame.QuestaoTextoLongo.pas' {FrameQuestaoTextoLongo: TFrame},
  Model.EleicaoQuestao in 'Form\Eleicao\Model\Model.EleicaoQuestao.pas',
  Controller.EleicaoQuestao in 'Form\Eleicao\Controller\Controller.EleicaoQuestao.pas',
  UnitFrmAddWhatsapp in 'Form\Sistema\UnitFrmAddWhatsapp.pas' {FrmAdicionarWhatsApp},
  Model.AssociadoAtualizarAPI in 'Form\ModelE\Sindicato\Model.AssociadoAtualizarAPI.pas',
  Controller.AssociadoAtualizacaoAPI in 'Form\Controllers\Sindicato\Controller.AssociadoAtualizacaoAPI.pas',
  UnitControleSindicato in 'Form\ModuloAssociaao\Sindicato\UnitControleSindicato.pas' {FrmAssociadoSindicato},
  UnitAssociadoProcessarAtualizacao in 'Form\ModuloAssociaao\Sindicato\UnitAssociadoProcessarAtualizacao.pas' {FrmAssociadoProcessarAtualizacao},
  DAO.AssociadoAtualizacaoAPI in 'Form\Dao\Sindicato\DAO.AssociadoAtualizacaoAPI.pas';

{$R *.res}
var
  hMutex: THandle;
  MutexName: string;
begin

  //codigo para impedir abertura do sistema 2x
  MutexName := 'Easyone'; // Nome único para o seu programa
  hMutex := CreateMutex(nil, True, PChar(MutexName));

  if (hMutex = 0) or (GetLastError = ERROR_ALREADY_EXISTS) then
  begin
    MessageBox(0, 'O aplicativo EasyOne já está em execução!', 'Atenção', MB_OK or MB_ICONWARNING);
    Exit;
  end;

  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'EasyOne Systems';
  Application.CreateForm(TFrmPrincipalNew, FrmPrincipalNew);
  Application.CreateForm(TDM, DM);
  Application.CreateForm(TDMRotinas, DMRotinas);
  Application.CreateForm(TDMAPP, DMAPP);
  Application.CreateForm(TDMRelatorio, DMRelatorio);
  FrmPrincipalNew.Caption  := AppName;

  Application.Run;

  CloseHandle(hMutex);
end.
